Translating WebAssembly tutorial in Romanian
UPB-CS-OpenSourceUpstream/tour_of_rust pull request #14
Opened 2023-12-23 11:52 UTC by mariapana

2024-01-07 16:41 UTC, alexandruradovici reviewed
Te rog verifica textul in romana, sunt multe exprimari ce jnu exista. E ok sa folosetsi google translate, dar trebui sa aranjezi textul.

2024-01-07 16:41 UTC, alexandruradovici commented on wasm/ro/chapter_0.yaml
> +    și modul în care Rust poate fi folosit pentru a alimenta web-ul. Dacă este prima oară
*a alimenta web-ul* nu suna in romana.

2024-01-07 16:41 UTC, alexandruradovici commented on wasm/ro/chapter_1.yaml
> +    ca alternativă pentru JavaScript, având niște avantaje speciale:
```suggestion
    A fost dezvoltat pentru browser
    ca alternativă pentru JavaScript, având niște avantaje speciale:
```

2024-01-07 16:41 UTC, alexandruradovici commented on wasm/ro/chapter_1.yaml
> +    * Deoarece este un low level bytecode, este capabil să facă operații matematice
```suggestion
    * Deoarece este un cod binar apropiat de hardware, este capabil să facă operații matematice
```

2024-01-07 16:41 UTC, alexandruradovici commented on wasm/ro/chapter_1.yaml
> +    * WebAssembly a fost proiectat pentru a fi "host agnostic", permițând unor oameni
```suggestion
    * WebAssembly a fost proiectat pentru a fi independent de platformă, permițând 
```

2024-01-07 16:41 UTC, alexandruradovici commented on wasm/ro/chapter_1.yaml
> +    să folosească WebAssembly și [în afara browserelor](https://wasmer.io/)!
```suggestion
    folosirea sa și [în afara browserelor](https://wasmer.io/)!
```

2024-01-07 16:54 UTC, mariapana commented
Buna seara, domnule profesor!

Va multumesc pentru raspuns! Va asigur ca nu am intentionat niciodata sa folosesc si nici nu vad de ce as folosi Google Translate sau alte forme automate de traducere. Traducerea a fost facuta pornind de la premisa de a nu schimba prea mult termenii tehnici pentru a evita eventuale pierderi de informatii sau nuante de exprimare in urma adaptarii. Imi pare rau daca traducerea nu a fost conform asteptarilor, o voi modifica conform sugestiilor dumneavoastra.

2024-01-07 17:09 UTC, alexandruradovici commented
Este perfect ok sa folosetsi orice sistem de tracducere, te rog doar verifica ca ce e scris este corect in limba romana.

2024-01-07 21:59 UTC, Alexe1289 approved these changes
Cred ca ar trebui o reformulare aici.

2024-01-07 21:59 UTC, Alexe1289 commented on wasm/ro/chapter_2.yaml
> +    Nu doriți să pasați peste tot o structură de date "învelită" ca octeți?
Nu doriți să transmiteți peste tot o structură de date plină de octeți?

2024-01-07 21:59 UTC, Alexe1289 commented on wasm/ro/chapter_2.yaml
> +    care sunt mult mai fin definite decât în Javascript. Verificați
Verificați dacă biblioteca limbajului dumneavoastră de programare oferă funcționalități care vă pot ajuta să găsiți un mod mai simplu de rezolvare.

2024-01-07 22:12 UTC, Alexe1289 commented on wasm/ro/chapter_2.yaml
> +    Nu doriți să pasați peste tot o structură de date "învelită" ca octeți?
```suggestion
    Nu doriți să transmiteți peste tot o structura plină de octeți?
```

2024-01-07 22:12 UTC, Alexe1289 commented on wasm/ro/chapter_2.yaml
> +    a găsi un mod mai ușor de a rezolva sarcina!
```suggestion
    care sunt mult mai fin definite decât în Javascript. Verificați
    dacă limbajul dumneavoastră de programare oferă funcționalități care să vă
    ajute la rezolvarea problemei

2024-01-08 09:28 UTC, octavianarmasu requested changes

2024-01-08 09:28 UTC, octavianarmasu commented on wasm/ro/chapter_2.yaml
> +    Trecerea graniței între gazdă și WebAssembly este o anevoioasă,
```suggestion
    Trecerea graniței între gazdă și WebAssembly este anevoioasă,
```
Typo: un o in plus

2024-01-08 09:31 UTC, octavianarmasu commented on wasm/ro/chapter_3.yaml
> +    Pentru e trece peste acest obstacol, trebuie să stabilim o convenție de a folosi
```suggestion
    Pentru a trece peste acest obstacol, trebuie să stabilim o convenție de a folosi
```
Typo e in loc de a

2024-01-08 09:33 UTC, octavianarmasu commented on wasm/ro/chapter_3.yaml
> +    dincolo de sfera acestui tutorial. Ne-am putea imagina o implementae foarte simplă a
```suggestion
    dincolo de sfera acestui tutorial. Ne-am putea imagina o implementare foarte simplă a
```
Typo: implementare in loc de implementae

2024-01-08 09:34 UTC, tudor-cretu requested changes

2024-01-08 09:34 UTC, tudor-cretu commented on wasm/ro/chapter_3.yaml
> +    * trebuie să pasăm corpul funcției pe care dorim să o creăm în JavaScript
```suggestion
    * trebuie să transmitem corpul funcției pe care dorim să o creăm în JavaScript
```
Consider că "transmitem" este un echivalent mai bun în limba română.

2024-01-08 09:34 UTC, tudor-cretu commented on wasm/ro/chapter_3.yaml
> +    După cum putem vedea, pentrz a comunica corect obiecte, avem nevoie de un fel de
```suggestion
    După cum putem vedea, pentru a comunica corect obiecte, avem nevoie de un fel de
```
Typo, "pentru" în loc de "pentrz".

2024-01-08 09:34 UTC, tudor-cretu commented on wasm/ro/chapter_3.yaml
> +    un obiect este stocat în vector și indexul său este returnat ca
```suggestion
    un obiect este stocat în vector și indicele său este returnat ca
```
Consider că acest cuvânt poate fi tradus în română, fără a-și pierde sensul.

2024-01-08 10:00 UTC, mariapana commented on wasm/ro/chapter_2.yaml
> +    Nu doriți să pasați peste tot o structură de date "învelită" ca octeți?
Mulțumesc pentru semnalare! Contextul se referea la reprezentarea structurii, nu la conținutul ei. Așadar, cred că o modificare adecvată ar fi:
```suggestion
    Nu doriți să transmiteți peste tot o structură de date reprezentată sub formă de octeți?
```

2024-01-08 10:01 UTC, octavianarmasu commented on wasm/ro/chapter_2.yaml
> +    // sub array ia indexul de început și de sfârșit
```suggestion
    // sub array ia indicele de început și de sfârșit
```

2024-01-09 13:28 UTC, andrei-27 requested changes

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_1.yaml
> +    * Are în vedere și izolarea, permițând controlul fin al accesului.
```suggestion
    * Acesta are în vedere izolarea, permițând controlul fin al accesului.
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_1.yaml
> +    într-un format "human readable".
```suggestion
    într-un format lizibil.
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_1.yaml
> +    începe să ne uităm în detaliu la modul cum JavaScript și WebAssembly pot comunica
```suggestion
    începe să ne uităm în detaliu la modul în care JavaScript și WebAssembly pot comunica
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    Javascript reprezintă un șir lung de octeți ca un `ArrayBuffer`.
```suggestion
    Javascript reprezintă un șir lung de octeți sub forma unui `ArrayBuffer`.
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    // modifica array buffer-ul
```suggestion
    // modifică array buffer-ul
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    // crează un șir de 8 octeți
```suggestion
    // creează un șir de 8 octeți
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    Javascript oferă funcții de utilitate pentru a scrie/citi string-uri UTF-8
```suggestion
    Javascript oferă funcții utilitare pentru a scrie/citi string-uri UTF-8
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    Să explorăm conceptul opus. Imaginați-vă că dorim să dăm niște text
```suggestion
    Să explorăm conceptul opus. Imaginați-vă că dorim să furnizăm un text
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    1. Să determinăm lungimea în bytes a textului pe care vrem să-l dăm.
```suggestion
    1. Să determinăm lungimea în octeți a textului pe care vrem să îl furnizăm.
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    3. Să copiem bytes în memoria programului nostru la începutul spațiului
```suggestion
    3. Să copiem octeții în memoria programului nostru la începutul spațiului
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    anumit indice de început și lungime în bytes.
```suggestion
    anumit indice de început și lungime specificată în octeți.
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    Iată un exemplu de cum ar arăta acea inițializare:
```suggestion
    Iată un exemplu despre cum arată acea inițializare:
```

2024-01-09 13:28 UTC, andrei-27 commented on wasm/ro/chapter_2.yaml
> +    // Transformă "Ferris" în bytes
```suggestion
    // Transformă "Ferris" în octeți
```

2024-01-11 09:49 UTC, mariapana commented on wasm/ro/chapter_1.yaml
> +    * Are în vedere și izolarea, permițând controlul fin al accesului.
Punctul anterior (vezi randul 11) foloseste deja expresia "avand in vedere". Asadar, acel "si" continua ideea, evitand repetarea expresiei.

2024-01-11 09:51 UTC, mariapana commented on wasm/ro/chapter_1.yaml
> +    într-un format "human readable".
"Lizibil" este de obicei folosit în contexte precum scrisul de mână, fapt reflectat inclusiv de sinonimele propuse de dexonline. În situația noastră, consider că nu se potrivește.

2024-01-11 09:52 UTC, mariapana commented on wasm/ro/chapter_1.yaml
> +    începe să ne uităm în detaliu la modul cum JavaScript și WebAssembly pot comunica
Exprimările sunt echivalente și corecte. Schimbarea e redundantă.

2024-01-11 09:54 UTC, mariapana commented on wasm/ro/chapter_2.yaml
> +    Javascript reprezintă un șir lung de octeți ca un `ArrayBuffer`.
Exprimările sunt echivalente și corecte. Modificarea este redundantă.

2024-01-11 09:56 UTC, mariapana commented on wasm/ro/chapter_2.yaml
> +    Iată un exemplu de cum ar arăta acea inițializare:
Exprimările sunt echivalente și corecte. Modificarea este redundantă.

2024-01-12 19:56 UTC, andreigheta requested changes

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_2.yaml
> +    Javascript și programul dumneavoastră de WebAssembly au reprezentări
```suggestion
    JavaScript și programul dumneavoastră de WebAssembly au reprezentări
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_2.yaml
> +    Așadar, pentru a comunica între Javascript și WebAssembly, va trebui
```suggestion
    Așadar, pentru a comunica între JavaScript și WebAssembly, va trebui
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_2.yaml
> +    Șirurile de octeți pot fi de asemenea scrise direct în memoria unui program
```suggestion
    Șirurile de octeți pot fi, de asemenea, scrise direct în memoria unui program
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_2.yaml
> +    Javascript reprezintă un șir lung de octeți ca un `ArrayBuffer`.
```suggestion
    JavaScript reprezintă un șir lung de octeți ca un `ArrayBuffer`.
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_2.yaml
> +    Javascript oferă funcții utilitare pentru a scrie/citi string-uri UTF-8
```suggestion
    JavaScript oferă funcții utilitare pentru a scrie/citi string-uri UTF-8
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_2.yaml
> +    care sunt mult mai fin definite decât în Javascript. Verificați
```suggestion
    care sunt mult mai fin definite decât în JavaScript. Verificați
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_2.yaml
> +    Javascript și "garbage collection".
```suggestion
    JavaScript și "garbage collection".
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_3.yaml
> +    Am văzut în primele capitole că putem foarte ușpr să scriem manual propriile
```suggestion
    Am văzut în primele capitole că putem foarte ușor să scriem manual propriile
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_3.yaml
> +    funcții JavaScript în fișierele noaste `.js`. Așa că
```suggestion
    funcții JavaScript în fișierele noastre `.js`. Așa că
```

2024-01-12 19:56 UTC, andreigheta commented on wasm/ro/chapter_3.yaml
> +    mai târziu cu parametrii
```suggestion
    mai târziu cu parametri
```

2024-01-19 16:08 UTC, alexandruradovici requested changes

2024-01-19 16:08 UTC, alexandruradovici commented on wasm/ro/chapter_0.yaml
> +    și modul în care Rust poate fi folosit pentru a dezvolta web-ul. Dacă este prima oară
```suggestion
    și modul în care Rust poate fi folosit pentru a dezvolta aplicații web. Dacă este prima oară
```

2024-01-21 13:31 UTC, alexandruradovici approved these changes
Please send this to upstream and place a link to it here.

2024-01-21 13:47 UTC, mariapana commented
Here is the link to the PR:
https://github.com/richardanaya/tour_of_rust/pull/498

2024-01-22 10:23 UTC, closed without merging