Added Explanations
UPB-CS-OpenSourceUpstream/tour_of_rust pull request #15
Opened 2023-12-25 23:50 UTC by TrifanBogdan24

Here are some changes I made and my approach of Tour of Rust:
- a few words about what is Rust and its unique aspects
- working in terminal with Rust (compiling, running and cargo commands) 
- macros
-  detailed information about data types and collections
- self and Self in terms of implementing a static / non-static method for a struct
- how to work with cargo

2023-12-26 00:00 UTC, TrifanBogdan24 commented
Solved issues:
- #431 (https://github.com/richardanaya/tour_of_rust/issues/431#issue-1167495785)
- #423 (https://github.com/richardanaya/tour_of_rust/issues/423)
- #306 (https://github.com/richardanaya/tour_of_rust/issues/306)
- #289 (https://github.com/richardanaya/tour_of_rust/issues/289)

Added features:
- a few words about Rust and its unique aspects
- terminal commands (compiling, running a Rust executable, cargo)
- detailed information about data types and collections
- how to use cargo
- the differences between a library and a binary crate
- pointer

2024-01-07 16:41 UTC, alexandruradovici requested changes
Delete the `.idea` folder from the repository.

2024-01-07 16:43 UTC, alexandruradovici commented
Split this in two pull requests, one that fixes the existing chapters and one that adds the extra chapter.

2024-01-08 15:44 UTC, iulianalexa requested changes

2024-01-08 15:44 UTC, iulianalexa commented on lessons/en/chapter_4.yaml
> +    stop, unwinding the stack and cleaning up resources along the way.
stops*

2024-01-08 15:44 UTC, iulianalexa commented on lessons/en/chapter_9.yaml
> +    Now, is no longer required to use `extern crate` in code.
it is no longer*

2024-01-08 17:01 UTC, closed without merging

2024-01-08 17:05 UTC, TrifanBogdan24 commented
The changes are split in the following two different Pull Request:
- https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/19 on branch `fixing`
- https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/20 on branch `new-chapter`