translated chapter 10 in romanian
UPB-CS-OpenSourceUpstream/tour_of_rust pull request #18
Opened 2024-01-06 16:43 UTC by aniakchak09

2024-01-07 16:45 UTC, alexandruradovici requested changes
Delete the `.idea` folder from the repository.

2024-01-15 09:48 UTC, alexandruradovici commented
Please send this to upstream and place a link to it here.

2024-01-15 09:49 UTC, alexandruradovici requested changes

2024-01-15 09:49 UTC, alexandruradovici commented on lessons/ro/chapter_10.yaml
> +    te-ai simțit bine până acum, îți recomandăm să continui cu resursele:
```suggestion
    ți-a plăcut acest tutorial, îți recomandăm să continui cu resursele:
```

2024-01-19 09:02 UTC, alexandruradovici approved these changes

2024-01-19 09:02 UTC, alexandruradovici commented
Send this pull request to upstream and place a link to it here.

2024-01-19 11:22 UTC, aniakchak09 commented
https://github.com/richardanaya/tour_of_rust/pull/496

2024-01-22 10:22 UTC, closed without merging