Translated chapter 5 in german
UPB-CS-OpenSourceUpstream/tour_of_rust pull request #27
Opened 2024-01-20 14:03 UTC by andreialex6

I translated chapter 5 in german.

2024-01-20 20:49 UTC, teodorobert requested changes
Thank you for your contribution.

This is just a preliminary review, I do not speak enough German to vouch for the accuracy of the translation.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20%2F%2F%20Instan%C8%9Biem%20struct
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +  code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20foo_a%20%3D%20Foo%20%7B
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Bar%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Astruct%20Foo%20%7B%0A%20%20%20%20bar%3A%20Bar%2C%0A%7D%0A%0Afn%20
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Afn%20do_something(f%3A%20Foo)%20%7B%0A%20%20%20%20println!(%22%7B
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Afn%20do_something()%20-%3E%20Foo%20%7B%0A%20%20%20%20Foo%20%7B%20
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20foo%20%3D%20Foo%20%7B%20x%3
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Afn%20do_something(f%3A%20Foo)%20%7B%0A%20%20%20%20println!(%22%7B
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=fn%20main()%20%7B%0A%20%20%20%20let%20mut%20foo%20%3D%2042%3B%0A%20%20%20%20let%20f%20%3D%20%26mut%20foo%3B%0A%20%20%20%20l
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Afn%20do_something(f%3A%20%26mut%20Foo)%20%7B%0A%20%20%20%20f.x%20
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0Afn%20do_something(a%3A%20%26Foo)%20-%3E%20%26i32%20%7B%0A%20%20%2
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0A%2F%2F%20parametrul%20foo%20%C8%99i%20valoarea%20de%20retur%20au%
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=struct%20Foo%20%7B%0A%20%20%20%20x%3A%20i32%2C%0A%7D%0A%0A%2F%2F%20foo_b%20%C8%99i%20valoarea%20de%20retur%20au%20aceea%C8%
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=static%20PI%3A%20f64%20%3D%203.1415%3B%0A%0Afn%20main()%20%7B%0A%20%20%20%20%2F%2F%20variabilele%20statice%20pot%20fi%20%C3
Please translate the code to German or use the English version instead of the Romanian version.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    * Dies wird in C++ auch als Resource Acquisition Is Initialization (RAII) bezeichnet.
"Resource Acquisition is Initialization" can be translated to German: [Ressourcenbelegung ist Initialisierung](https://de.wikipedia.org/wiki/Ressourcenbelegung_ist_Initialisierung)
```suggestion
    * Dies wird in C++ auch als Ressourcenbelegung ist Initialisierung (RAII) bezeichnet.
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +
Insert a paragraph break like in the original text:
```suggestion


```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    Referenzen ermöglichen uns den Zugriff auf eine Ressource mit dem Operator '&'.
Use backticks for inline code:
```suggestion
    Referenzen ermöglichen uns den Zugriff auf eine Ressource mit dem Operator `&`.
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    Mit dem Operator „&mut“ können wir auch veränderlichen Zugriff auf eine Ressource ausleihen.
Use backticks for inline code:
```suggestion
    Mit dem Operator `&mut` können wir auch veränderlichen Zugriff auf eine Ressource ausleihen.
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    Mithilfe von '&mut'-Referenzen können Sie den Wert des Eigentümers mithilfe des '*'' festlegen
Use backticks for inline code:
```suggestion
    Mithilfe von `&mut`-Referenzen können Sie den Wert des Eigentümers mithilfe des `*` festlegen
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    * Eine Referenz darf niemals **länger leben** als ihr Besitzer.Eine Referenz darf niemals **länger leben** als ihr Besitzer.
Accidental repetition:
```suggestion
    * Eine Referenz darf niemals **länger leben** als ihr Besitzer.
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +
Insert a paragraph break like in the original text:
```suggestion


```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    '`Statische' Ressourcen werden niemals **verloren**.
Do not translate Rust keywords:
```suggestion
    `'static` Ressourcen werden niemals **verloren**.
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    Wenn statische Lebenszeitressourcen Referenzen enthalten, müssen sie alle `'statisch` sein
Do not translate Rust keywords:
```suggestion
    Wenn statische Lebenszeitressourcen Referenzen enthalten, müssen sie alle `'static` sein
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    * Rust erlaubt die Verwendung von „unsafe { ... }“-Blöcken, um einige Operationen auszuführen
Use backticks for inline code:
```suggestion
    * Rust erlaubt die Verwendung von `unsafe { ... }`-Blöcken, um einige Operationen auszuführen
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +- title: Capitolul 5 - Abschluss
Translate "Capitolul" to German:
```suggestion
- title: Kapitel 5 - Abschluss
```

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +    überwältigend. Es ist wichtig, sich daran zu erinnern
Remove trailing whitespace:
```suggestion
    überwältigend. Es ist wichtig, sich daran zu erinnern
```

2024-01-20 20:49 UTC, ghost commented on lessons/de/chapter_5.yaml
> +
Remove trailing whitespace:
```suggestion

```
**Note:** The suggestion shows removing the line entirely, it should be an empty line instead.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +
Remove trailing whitespace:
```suggestion

```
**Note:** The suggestion shows removing the line entirely, it should be an empty line instead.

2024-01-20 20:49 UTC, teodorobert commented on lessons/de/chapter_5.yaml
> +
Remove trailing whitespace:
```suggestion

```
**Note:** The suggestion shows removing the line entirely, it should be an empty line instead.

2024-01-20 20:49 UTC, ghost commented on lessons/de/chapter_5.yaml
> +    * Vergessen, Ressourcen abzubauen
Remove trailing whitespace:
```suggestion
    * Vergessen, Ressourcen abzubauen
```

2024-01-21 00:29 UTC, andreialex6 commented
Thank you for your help ! I took your suggestions into consideration and resolved most of them !

2024-01-22 19:15 UTC, closed without merging

2024-01-23 07:09 UTC, teodorobert commented
This was merged to upstream in its current state: https://github.com/richardanaya/tour_of_rust/pull/502